version = 0.1

[default.deploy.parameters]
stack_name = "clouddocs-backend"
resolve_s3 = true
s3_prefix = "clouddocs-backend"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
